### ISSUE TITLE
Advanced deconstruction table not yielding RP

### ISSUE THREAD

**Issue by Seygantte** [theflogat/Technomancy#101]
Hello

Testing this machine on a multiplayer server. Benchmarked Terra at 128 and then fed it 6 stacks of dirt via a hopper. Final result at 129 Terra research points. Is this intended behaviour?
Using TECHNOMANCY - 9.19.L - 1.7.10
with THAUMCRAFT-1.7.10-4.2.3.5
and assorted other add ons in resonant rise 3.2.6.4-RC

Sey

**Comment by Mordenkainen** [comment]
Yes, that is the intended behavior. If you break down worthless things to get RP, you get little to no RP.

This is the same as the standard table, except only produces an RP 1 in 8 times the normal table would.

Here is how the standard table calculates your chance of getting an RP:
Dirt = 2 Terra = 2 Primals = 2 in 80 chance of getting an RP = 2.5% chance of getting an RP

For the automated table the chance is 1/8th what it would be in the standard table, so in the case of Dirt, 0.3% chance.

For a better chance use crafting tables, which end up being about a 12% chance of getting an RP.

**Comment by Seygantte** [comment]
I see. I knew it would yield RP more slowly than a standard table, but thought that meant it was consuming each item at a lower rate, not that it's being more cost intensive on the items.

I know that crafting tables are a good source, I only used dirt because it meant I only had Terra to check.

Thanks for the response.
