### ISSUE TITLE
Energy Condenser without means to extract Potentia

### ISSUE THREAD

**Issue by Medason** [theflogat/Technomancy#111]
I have recently updated tot he 0.11.0 version.  After the update I am no longer able to find a way to get Potentia from the Energy Condenser.  Have tried both Tubes and Coils. All sides.  Even Phials wont work.  No error messages or other issues.

**Comment by Mordenkainen** [comment]
I believe the Condenser was recently changed to support configurable output sides.

The state of a side can be changed by clicking on it with a wrench. Try clicking with a wrench on a side and seeing if you can extract Potentia from that side. If you can then close this issue. Otherwise update the issue and we'll see if we can figure out what is going on.

Also, I do not believe Phials ever worked for the Condenser, but it might be a nice enhancement!

**Comment by Medason** [comment]
No, I figured it out, between the last version and this new version, the block got glitched.  Once I pulled it out and replaced it with a fresh one it worked fine.  I think it might have something to do with being maxed out on internal RF and then changing versions might have something to do with it. Because it was just stuck on full RF and full potentia, but once I replaced it with a wholy new one cheated in, it worked perfectly.

**Comment by Medason** [comment]
Okay, I solved the problem.  Between 0.10.j and upgrading to 0.11.0, the condenser in question was full of RF and full of Potentia, 5,000,000/5,000,000 and 64/64(I assume, never seen it go higher) respectively.  After updating to 0.11.0 the condensor wouldn't get an output no matter how much I picked it up, placed it down, turned it, whacked it with a wrench.  It was only after replacing it with a completely fresh one(cheated in, I know...) that the condensor started to work as understood.  Hope this knowledge helps anyone else who has this problem.

**Comment by Medason** [comment]
P.S.
>Also, I do not believe Phials ever worked for the Condenser, but it might be a nice enhancement!
I know, I love seeing my golems lumbering around my lab, it would be awesome to see them pulling of the condensor as well.

**Comment by Mordenkainen** [comment]
ok, after a look at the code and some testing, it looks as if the solution to the problem was just to Sneak-Right-Click the side you wanted to output on.

Closing this for the time being, but I will open an enhancement for allowing Phials and Golems to interact with the Condenser.
