### ISSUE TITLE
Thaumic Pipe Can't Connect to Node Fabricator

### ISSUE THREAD

**Issue by Alaberti** [theflogat/Technomancy#119]
So for today's enhancement. I was trying to hook up Thaumic Pipes (by Jezza) to the node fabricator and found they didn't connect at all. I hadn't tried other things, but the theory would probably work out the same. Is this something that needs special interaction from your end, or their end? Thanks as always!

**Comment by Mordenkainen** [comment]
Thaumic Pipes plays games with the Essentia Transport API.

This is not a bad thing, but it means that it does not play well with things that do not follow the API 100%

Technomancys blocks do not follow the API 100%, sort of on purpose, so it does not come as a surprise that TP doesn't play well with them.

I'll leave the issue open, but I don't know that it will get fixed.

As a side note, I have always had issues with essentia getting "lost" when using TP. Perhaps they have fixed it, but I use Essentia coils for that stuff now.

**Comment by Alaberti** [comment]
Fair enough - TP has been useful when I don't have a very, ah, open space to work with.

**Comment by Mordenkainen** [comment]
OK, just looked at this a bit more and it looks like TP may have changed over to requiring mods to add support for any "non-standard" items.

I think you will find that TP pipes will connect to the Quantum Jar without any issues, but not much else. I will see if there is anything that can be done about this.

**Comment by Mordenkainen** [comment]
Note: The Node Fabricator and Essentia Fusor still can not connect the Thaumic Pipes. This is due to Thaumic Pipes not having support for a block that both input and outputs Essentia without having specific sides for this purpose.
