### ISSUE TITLE
Suggestion: RF Alchemic Furnace

### ISSUE THREAD

**Issue by Megistus** [theflogat/Technomancy#120]
As the title states ... an RF powered furnace for alchemical operations.

**Comment by Mordenkainen** [comment]
This is already supported.

Put a Galvanized Bellows on an Alchemical Furnace. This will cause the furnace to use RF (via the Bellows) instead of fuel, and to break down Essentia at the same speed as if it was fueled with Alumentum.

**Comment by Megistus** [comment]
Well ... how about that ... completely missed it! Thanks!
