### ISSUE TITLE
Technomnacy Tab Overlaying Magic Bees tabs And cant Click On It

### ISSUE THREAD

**Issue by RoloEdits** [theflogat/Technomancy#125]
![2015-07-02_05 13 34](https://cloud.githubusercontent.com/assets/12489689/8476768/51693454-2079-11e5-9aeb-6d20b3dfa8a3.png)

![2015-07-02_05 13 36](https://cloud.githubusercontent.com/assets/12489689/8476769/54e02f2a-2079-11e5-8c97-51a039d55cbf.png)

**Comment by Mordenkainen** [comment]
This an a known issue with Thaumcraft. There hits a point that it can not display more tabs in the Thaumonomicon and what you are seeing happens.

Unfortunately I believe the only fix is to remove one of the mods that adds a tab.

**Comment by RoloEdits** [comment]
Ok Thanks For The Quick Response I'll Just Remove One Of The Mods Then
