### ISSUE TITLE
Galvaniced Bellows not usable with Automagy's Alchemical Boiler

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [theflogat/Technomancy#126]
What I mean is this: http://i.imgur.com/de8yhlF.jpg

Can't use the Galvaniced Bellows!

**Comment by theflogat** [comment]
Ok. It's either a change in the Thaumcraft API or it's automagy's fault.

**Comment by Mordenkainen** [comment]
Automagy is closed source.

The Galvanized bellows directly manipulate some of the internal states of the blocks it interacts with to produce its effects.

To make the Bellows work with Automagy would either require the author of Automagy to add some hooks into their API to allow this, or for us to poke around at code we aren't supposed to.

My opinion is that we should close this issue and revisit it if and when Automagy gives us the ability to do this type of interaction with the boiler.

**Comment by Tuhljin** [comment]
I'm open to adding something to the Automagy API to support this but I'm not sure exactly what you'd need. Which variables do you need access to? The bellows count? Smelting time needed for the current operation? Smelting time passed on the current operation?

**Comment by Mordenkainen** [comment]
For the arcane furnace the bellows alters the fuel burn time (so that the furnace runs on RF instead of fuel), and the flag that says the furnace has been fueled with alumentum (to increase the rate at which the "essentia slurry" is broken down).

Additionally it checks the aspects of what is in the furnace so that it wont fuel it if the item in it has no aspects.

I'm not sure how much of that applies to the boiler.

**Comment by Unrepentant-Atheist** [comment]
This is why I love open source. Devs from different project working together to make an application/game/mod better for everyone!

**Comment by Mordenkainen** [comment]
@Tuhljin
These are the fields we would need access to:
furnaceBurnTime - Modify fuel level (READ/WRITE)
speedBoost - Pretend to be fueled by Alumentum (WRITE)
vis - Currently Stored Vis (READ)
MAX_VIS - Max vis that can be stored (READ)

They are all public except for speedBoost.

I can add support via reflection, which will involve changing speedBoosts visibility. The code would be virtually identical for what we do for the Alchemical Furnace.

If you don't mind the use of reflection, and don't see yourself making any large scale changes to the code in the near future let us know and we will go that way.

If you would rather provide an alternate way, no problem, just let us know.

**Comment by Tuhljin** [comment]
I will try to add some public getters and setters for you in the next version of Automagy, but reflection is fine by me if you don't want to wait. I don't have any plans to change the way it works.

**Comment by theflogat** [comment]
Thank you for responding. I think an interface would be the best choice since it'll allow for full compatibility with future blocks.

**Comment by Tuhljin** [comment]
The next release of Automagy (to be released today) will include this interface: https://github.com/Tuhljin/Automagy/blob/master/src/main/java/tuhljin/automagy/api/essentia/IEssentiaDistillery.java

**Comment by Mordenkainen** [comment]
Excellent! Thanks!
