### ISSUE TITLE
Orderly Lamps Not Nullifying Instability

### ISSUE THREAD

**Issue by RoloEdits** [theflogat/Technomancy#128]
In The Thauminimicon Entry It Say 5 Lamps Should Nullify Instability But Even With 5 Its Still Unstable At Times.Or Mabey Im Doing Something Wrong      v0v

![2015-07-03_22 14 54](https://cloud.githubusercontent.com/assets/12489689/8506721/e2211da4-21d7-11e5-9480-6890c7b16df4.png)

![2015-07-03_22 15 08](https://cloud.githubusercontent.com/assets/12489689/8506722/e6f9fc60-21d7-11e5-9f3a-7ab39871ef13.png)

I Have Buildcraft Void Fluid Pipes On The Bottom.

...Should I Be Saving It???

Thanks For Help

**Comment by Mordenkainen** [comment]
I think you need to put a tank of some kind under the lamps, then void the fluid out of the tanks.

**Comment by Mordenkainen** [comment]
Actually, I take that back, it should still work with just the void pipes, as long as they are set up to suck out the flux goo. (using a gate or some such).

And 5 is just a guideline. If you are doing really dangerous infusions you may need even more.

**Comment by RoloEdits** [comment]
ok thank you ill try your suggestions

**Comment by RoloEdits** [comment]
and also i believe you need to have a wooden pipe that extracts with an autarchic gate.

Suggestion: Auto Output From Orderly Lamp

would make for nice simple compact builds

**Comment by SteamCrunk** [comment]
Confirming that these lamps are currently non functional.  I have one right next to my altar, with a dedicated feed of Ordo, and fluid being pulled from the lamp out of the bottom.

It never even so much as begins to get a tick of flux, and it doesn't do a thing in terms of reducing stability.
![2015-07-12_06 06 17](https://cloud.githubusercontent.com/assets/6346641/8637696/8dd70692-285c-11e5-9aad-20d414b93c86.png)

Here's a picture of the lamp doing absolutely nothing while the altar explodes behind it.

**Comment by Mordenkainen** [comment]
Please retest this with beta 0.11.1A. I am unable to recreate. The lamps seem to be working fine for me.

**Comment by RoloEdits** [comment]
Yes, i just retested and they still don't seem to be working for me.They are not even sucking up any flux at all as i cant see any flux in there internal tanks or when piping out the bottom there is none arriving in a tank I set up.

**Comment by Mordenkainen** [comment]
What version of Thaumcraft are you using?

**Comment by RoloEdits** [comment]
Thaumcraft-1.7.10-4.2.3.5

**Comment by Mordenkainen** [comment]
What other Thaumcraft related mods do you have?

**Comment by RoloEdits** [comment]
Autogamy
Thaumic Tinkering
Magic Bees
Witching Gadgets
Forbidden Magic
Tainted Magic
Thaumic Additions
Thaumic Energistics
Thaumic Exploration
TC Node Tracker
Thaumcraft NEI
Nodal Mechanics

I Think this is all of them.

theres a few others that add thaumcraft stuff but are not really thaumcraft add-ons like rail craft and rotary craft and AOBD and a few others ill list them if you need me to

**Comment by Mordenkainen** [comment]
@SteamCrunk what mods do you have in common with that list. I am beginning to suspect that another mod may be altering the way instability is handled and interfering with the lamps.

**Comment by Mordenkainen** [comment]
Since there was no response, @RoloEdits is it possible for you to upload your modpack and a world with a setup that demonstrates the issue? This may help me narrow down the source.

**Comment by RoloEdits** [comment]
Yes I will but, its very unstable right now I've been experiencing a problem when I start my world and I suddenly start falling through the world. I'm guessing its a syncing issue because I cant open an inventories except my own and when I make any changes then exit and come back nothing is saved that I did like deleting items and other things.

**Comment by RoloEdits** [comment]
ill upload it any way but i think the problem is centered around twilight forest or thaumic additions with my weird desync

**Comment by RoloEdits** [comment]
unfortunately i will have to upload it tomorrow or later toady depending on what time it is for you

**Comment by Mordenkainen** [comment]
Ok, no problem, just let me know when its available.

**Comment by RoloEdits** [comment]
After removing thaumic additions because of a separate problem I was having, I went to set up a test world for you to download and after testing infusion it seems to be working now. Thaumic Additions adds stuff that was from TC2 so maybe they also changed the infusion properties as well.

**Comment by Mordenkainen** [comment]
OK, thanks. I will check that mod out and see if it also causes an issue for me.

**Comment by RoloEdits** [comment]
OK, I'm trying to remember if i removed any other mods lately as i have been removing a lot. i hit the max block id limit because of to many mods 320+.

**Comment by Mordenkainen** [comment]
So i havent actually loaded the mod, but a quick look at the code doesnt show anything that should break infusion... Perhaps you removed another mod?

Since it sounds like you have built a test world, start adding mods back until it breaks, than let me know what mod caused the issue.

**Comment by RoloEdits** [comment]
OK I will try adding mods that I remember removing(I have a folder for unused mods that im not using anymore but forget to move them there sometimes and just delete them by accident) one at a time so it might take me a little.

**Comment by RoloEdits** [comment]
I'vs tried the mods I removed and it still working so it must have been an update mod i'm still using that seems to have fixed it in one of there updates.

**Comment by RoloEdits** [comment]
or one that i forgot about

**Comment by Mordenkainen** [comment]
I'm closing this issue. If someone figures out what mod is interfering they can re-open it or open a new bug, but at this point there is nothing we can do to address the issue.

**Comment by Keridos** [comment]
Having the same issue here :-/
