### ISSUE TITLE
Node Fabricator - Essentia Intake

### ISSUE THREAD

**Issue by HandGrenade17** [theflogat/Technomancy#129]
So I have been using the Node Fabricator and when I connect the regular thaumcraft Jars with pipes to the Fabricator, only some of the time they will connect, and usually only shows for 1-2 clients. I did manage to get this to show correctly for 3 clients, and with redstone signal off, it still would not accept any essentia. It also has a full and constant flowing supply of power. Thanks :)

**Comment by Mordenkainen** [comment]
So what are you doing with the fabricator? Creating a node? Recharging a node? Adding Aspects to a node?

Do you have potency crystals installed?

Have you checked the suction the Fabricators are asking for to make sure it's being supplied with the right Essentia?

Do you have lightning bolts jumping between the two fabricators? Are the center hubs spinning?

The Fabricators are pretty much the most complicated devices in the mod, so a lot more info is needed to troubleshoot any problems with them.

**Comment by HandGrenade17** [comment]
Sorry, wasn't too sure what amount of information I needed to supply, lol. 

I'm creating a node, and I'm supplying it Aurangzeb and vintium

**Comment by HandGrenade17** [comment]
Oh my god, stupid phone. Sorry. I was using auram and vitium. I do have the Lightning bolts shooting between the two node fabricators, and the centre hubs are spinning. 

I did manage to fix it, but I have to put them up 1 off the floor and the nodes straight under the fabricator. Although, I still see this as an issue with the essentia pipes. :)

**Comment by Mordenkainen** [comment]
Nodes under the fabricators? If creating a node there shouldn't be any nodes near the fabricators.

You need to Supply Auram to the side creating pink lightning bolts, and Vitium to the side creating purple lightning bolts.

**Comment by HandGrenade17** [comment]
Again, extremely sorry, lack of information and stupid typo XD.

I was trying to use Essentia Pipes to pipe Auram and Vitium into the sides of the Node Fabricator (The correct sides). But the Node Fabricator was not accepting any Essentia. 

To fix it, I placed the *Jars* (Not Nodes, sorry lol) straight under the Fabricator, and it sucked directly from the jars, yet I am still not sure why the pipes wouldn't work. :)

**Comment by Mordenkainen** [comment]
Are you using normal essentia tubes or Thaumic Pipes?

**Comment by HandGrenade17** [comment]
Normal essentia tubes from 'Vanilla' Thaumcraft.

**Comment by Mordenkainen** [comment]
And you are using the 11.1 Technomancy?

**Comment by HandGrenade17** [comment]
Yeah :)

**Comment by HandGrenade17** [comment]
Seems like after a bunch of fiddling and putting the *Jars* straight under the Node Fabricator, I then tried the Essentia Tubes again and they seemed to work. I literally have no idea how or why, but yeah. Sorry for the inconvenience of time, and thank you for your help :)

**Comment by Mordenkainen** [comment]
I'll close this issue, and if you continue to see problems come back and re-open it.
