### ISSUE TITLE
Suggestion:Life Essence Infuser (Energetic Infuser)

### ISSUE THREAD

**Issue by RoloEdits** [theflogat/Technomancy#131]
i Would Be Cool If You Can "Recharge" items That Hold LP Like Orbs And Some Other Mods items Just Like You Would Item That Holds RF In An Energetic Infuser But By Pumping In Life Essence. So.So Instead Of Having To Wait Forever For You Orb It Fill Up When You've Got Tons Of LE Hanging Around You Can Do It Much Quicker. How Ever If You Don't Want It Super OP :( Then You Could Make This The Only Thing It Can Do.

i See There Is The Sanguine Infuser But i Have Not Been Able To Figure Out How to Use It. So It Might Do This But I Cant Seem To Pump In Liquids Or Put In Orbs.

**Comment by Mordenkainen** [comment]
The Sanguine Infuser takes LP from your Soul Network and uses it to process ores.

As far as your suggestion, none of those items actually "hold" LE, they just draw points from your Soul Network. So "charging" them is not really possible.
