### ISSUE TITLE
Suggestion Mana Transposer (Fluid Transposer)

### ISSUE THREAD

**Issue by RoloEdits** [theflogat/Technomancy#132]
Instead of waiting forever to get an ss rank terra shatterer if you could use mana condensate to infuse the mana it the item to fill it up as well as other things that can hold mana it would be a lot faster

**Comment by Mordenkainen** [comment]
I'm pretty sure that this would make Vaskii scream "broken balance!" so I don't think it's a good idea.

But, I'll leave final decisions to theflogat.

**Comment by RoloEdits** [comment]
OK, I'm not very good with balance so i'll leave that to you guys :P

**Comment by theflogat** [comment]
Sorry but no.
