### ISSUE TITLE
Crash | resources loaded on server?

### ISSUE THREAD

**Issue by alfw** [theflogat/Technomancy#149]
https://pastebin.com/w29G8QS4

**Comment by theflogat** [comment]
I swear, I hate @SideOnlys. I'll have a hotfix out tomorrow.

**Comment by alfw** [comment]
Any fix for this yet? ;P

**Comment by mrammy** [comment]
Fixed in https://github.com/theflogat/Technomancy/pull/150. Built and uploaded here for your convenience https://www.mediafire.com/?opilxs3vf0xud14. If the mod author wishes for me to take it down however, I will do so immediately

enjoy!
mrammy

**Comment by theflogat** [comment]
This version will probably cause issues so please take it down.

**Comment by theflogat** [comment]
Fixed in New Version.
