### ISSUE TITLE
Quantum Jars don't accept prefab labels

### ISSUE THREAD

**Issue by Alaberti** [theflogat/Technomancy#155]
Long time no see!

Great stuff so far. I was playing with pre-fabricating essentia labels so that I could tack them on empty jars, however I noticed right away that while this works on void and warded jars fine, attempting to apply the label to an empty quantum jar won't work. Once essentia is in it, it will take a pre-labeled label or a blank one just fine. Hope this is an easy fix, but if it isn't...thanks in advance yeah? *big smile*

**Comment by theflogat** [comment]
Nothing hard to fix. Took a weeklong break because of school so will only be fixed next week.

**Comment by Alaberti** [comment]
Hey, you do you, I get that lol
