### ISSUE TITLE
Galvanized Bellows spam dedicated server console when used on a vanilla furnace (during operation)

### ISSUE THREAD

**Issue by Alaberti** [theflogat/Technomancy#156]
This was a tricky one to track down; I noticed that my console was constantly incrementing from 1 to 200 in 2-3 count steps. It's nothing gamebreaking at least, just very inconvenient when trackingother issues from the console.

I'm sure this is just a return in a string output or something, but uh...couljd you fix this? You know you're the greatest right.

**Comment by theflogat** [comment]
Next version will have this removed.

**Comment by Mordenkainen** [comment]
Blah, sorry about that. My bad!

**Comment by theflogat** [comment]
Lol. No problem.
