### ISSUE TITLE
Small positioning issue with Order Lamps

### ISSUE THREAD

**Issue by WhiteZ** [theflogat/Technomancy#161]
Order lamps sharing a plane (X, Y or Z) with the infusion matrix fail to detect it (`getMatrix()` returns `null` even if the matrix is in range).

This is most likely due to this check ([TileFluxLamp.java:94](https://github.com/theflogat/Technomancy/blob/master/src/main/java/theflogat/technomancy/common/tiles/thaumcraft/machine/TileFluxLamp.java#L94)):
```java
if (xx != 0 && yy != 0 && zz != 0) {
```

I would guess something like `if (xx != 0 || yy != 0 || zz != 0)` was intended. I could submit a pull request, but it seems a tad overkill for just a simple one-line fix.

**Comment by Mordenkainen** [comment]
Actually I think a fix would be:
```java
if (xx == 0 && yy == 0 && zz == 0) {
    continue;
}

TileEntity te = this.worldObj.getTileEntity(this.xCoord + xx, this.yCoord + yy, this.zCoord + zz);
if(te instanceof TileInfusionMatrix) {
    return te;
}
```

But, that said, the conditional only prevents a single getTileEntity from being run, so doesn't save all that much in time anyway. The check should probably just be removed.
