### ISSUE TITLE
0.12.1+ green HUD element renders above everything else, including menus.

### ISSUE THREAD

**Issue by lossycrypt** [theflogat/Technomancy#162]
The new green HUD element is rendered above everything else i've tried so far. Including NEI and the options menu. Here's a screenshot from the snooper settings screen:
![technobat](https://cloud.githubusercontent.com/assets/14168854/10478678/90674d8e-725f-11e5-981a-201337ef4e30.jpg)

Reproduce:
Thaumcraft-1.7.10-4.2.3.5.jar
Baubles-1.7.10-1.0.1.10.jar
CodeChickenLib-1.7.10-1.1.3.140-universal.jar
Technomancy - 0.12.1C - 1.7.10.jar

Start a new world, the HUD element will show. Open any menu below it.

Besides the buggy rendering i don't think it's a good idea to have a permanent, position fixed hud element, because especially in bigger modpacks not everybody plays every mod. And it's very difficult to tell what mod HUD elements come from if you don't know them.

**Comment by theflogat** [comment]
Right. I'll fix this. To be honest, there is already client config that allows the player to disable it and I don't think it'd be hard to find that it comes from Technomancy.

**Comment by lossycrypt** [comment]
I don't see any option to disable it (Technomancy - 0.12.1C - 1.7.10), the only relevant config i can see are coordinates. Also as i haven't progressed far enough to know what the HUD is even used for i can't tell if it's a good idea to disable it ;). So maybe only show it when it is relevant? (I.e. the player has appropriate items/research progression.)
```
hud {
    I:StartX=16
    I:StartY=88
}
```

And with well over 100 mods it sure did take me some time to find where it comes from, because the only valid method for findnig out that i know is to just throw out half the mods and check if its still there, rinse and repeat. (This is not specific to your mod alone.)

**Comment by Alaberti** [comment]
I honest thought this hud came from AcademyCraft. What does it do? I don't see any documentation on it in the Thaumonomicon even after giving myself all research.

**Comment by theflogat** [comment]
It's almost featureless right now. To disable it, set the hudStartX to a negative value smaller than -10.

**Comment by theflogat** [comment]
-16

**Comment by Cbert** [comment]
theflogat, you have to know that your “green HUD element” caused lots of headache to many people, and personally I’m angry at you.

**Comment by theflogat** [comment]
It's because people don't bother to look for a way to disable it.

**Comment by Cbert** [comment]
Actually I did look for a way to disable it, luckily I’ve found this thread https://www.reddit.com/r/Minecraft/comments/3nb1va/which_minecraft_mod_is_adding_the_outlined_bar_in/
and saved some time on searching mode that put this bar on screen, from in pack with 250 mods. But still spend 4 hours. I hate you, you could signed next to hud param # annoying green bar at left side of screen.
So people can find it, and don’t get but hurt. But you didn’t thought about it, maybe because you’re an egoist, or some similar. Am I right?

**Comment by Alaberti** [comment]
Well that escalated quickly. I didn't think it was that big a deal. Since this is solved, however, think we could have this one closed and locked @theflogat?

**Comment by lossycrypt** [comment]
As long as it still renders wrongly this issue is infact not solved. Moving it off the screen is at most a temporary workaround. Also i know of no other mod-related hud element that renders permanently. So I'm still very much for only showing it when relevant. Whatever relevant in this case means. Btw it seems to render either full or empty depending on which mods are installed?

**Comment by theflogat** [comment]
Well, it's true that your analysis of me being egoist is completely flawless. As for closing or not this issue, I won't because people will keep opening them anyway so I'd rather have it all in the same "thread".
It being full or empty depends on your "natural" power. And moving it off screen is not a workaround. It's how it is supposed to be disabled.

**Comment by lossycrypt** [comment]
I meant it's a workaround for the "renders above things" not for dis-/enabling it. (Tho if that's the intended way of disabling it you might want to include a description line in the config file stating that to save you from further "analysis".). You said yourself it is "*almost* featureless right now." which would mean it has at least some features and disabling it might thus not be desired. Without knowing what those features are or when the feature-set is going to be extended this is impossible to judge of course.

Also it being full/empty for different mod-sets is based on what i saw it do in a brand new world respectively. I'm not sure what "natural power" is in your mod, but should that be different for brand new singleplayer worlds? (For the record mine has been full from the beginning and i haven't done anything magic related yet)

**Comment by Mordenkainen** [comment]
I have fixed the issue that causes this to render above everything else and have added a config option to disable the HUD entirely (Defaulted to not display until we actually use the indicator for something).

This will be available in the upcoming bug fix release.
