### ISSUE TITLE
Suggestion: Addendum to Essentia Coil research notes

### ISSUE THREAD

**Issue by Reassembly** [theflogat/Technomancy#165]
As mentioned in #164, Essentia Coils don't connect properly with vanilla-TC Alchemical Centrifuges, and possibly won't work with essentia-consuming equipment from *other* TC-mods that TM hasn't been coded to handle. However, Essentia Buffers can be used as a workaround - I'd like to suggest that this be mentioned "in-world" as an addendum to the Thaumonomicon entry for Essentia Coils, to "spin" this to the user as less of a "bug" and more of a "challenging feature".

*It has occurred to you that despite the essentia coil's simplicity and efficiency, the coil's resonant field may interfere with the very machinery it's attached to. Essentia crystallizers, and even Thaumatoriums, should be reliable enough, but more complex and esoteric thaumaturgical equipment might not function properly - or at all. Fortunately, in the process of working out the coil's operation, you established that as a fallback, Essentia Buffers are simple enough to be completely unaffected by a coil's resonance. You should be able to use a buffer as a safe "interface" to an essentia coil for any machines which cannot connect to one directly.*

**Comment by theflogat** [comment]
Well, this is be a pretty nifty workaround. Thanks.
