### ISSUE TITLE
Technoturges sceptre causes severe time out when near chargepads

### ISSUE THREAD

**Issue by Bennyboy1695** [theflogat/Technomancy#166]
Whenever a sceptre is near a Mekanism chargepad it causes a timeout so severe it forces the server to restart. Brought this as an issue here as the chargepad doesnt have a range of charging where as i expect the sceptre checks an area for something it can charge from. Heres the stacktrace that ultimately kills the server until either the wand is gone or the chargepad https://gist.github.com/Bennyboy1695/7e72e05649a88f1b51e1

**Comment by Mordenkainen** [comment]
The scepter does not have a range. It typically must be put in some sort of RF charger to charge.

The chargepad does have a range, though it is a fairly small one.

I expect that the chargepad is passing some unusual info to the scepter when it tries to charge it.

I have never been able to get Mek to run in the dev environment, so I'm not sure how to even begin troubleshooting this.

**Comment by Bennyboy1695** [comment]
Ah i wasnt aware of the range from the chargepad, but the report i got from the player was that it was a good 15-20 blocks away and caused this timeout still.

**Comment by Mordenkainen** [comment]
I have tried to replicate this and can not. Can you post a list of the mods you are using? There are some mods that patch wands, and I wonder if this is not related.

**Comment by Bennyboy1695** [comment]
This is the list of mods https://github.com/MyM-ModpackTeam/hypovolemia/tree/master/src/mods

**Comment by Mordenkainen** [comment]
Can you try to recreate this in single player and see if it happens there too?

**Comment by Bennyboy1695** [comment]
Seems we updated about 2 weeks ago which fixed the issue as i'm unable to recreate it either. So will close this now, thanks for the help anyway :smile:
