### ISSUE TITLE
Eldritch Consumer & Lava

### ISSUE THREAD

**Issue by Mohron** [theflogat/Technomancy#167]
Version: **0.11.1** via Resonant Rise 3.2.7.2-RC Project Flux

BLUF: Eldritch Consumer mines non-source lava blocks disrupting its operation once it hits a lava lake.

I placed my Eldritch consumer in the mining dim and had it working for a short time. after realizing it was not creating essence even though it was running, I then investigated. From just above bedrock I could see that lava was flowing downward because of the blocks below them had been removed. the same non-source blocks of lava were being mined by the machine over and over therefore nothing was being accomplished.

I would expect this machine to ignore non-source liquid blocks completely as they have no value and would avoid the problem I have seen.

**Comment by Mordenkainen** [comment]
That one was my call. I optimized the way the Consumer "eats" blocks and saw that issue at that time, though the issue had existed before then.

I chose to leave it the way it was because the alternative you describe causes server lag by generating large pools of flowing liquid. This is why so many servers ban Buildcraft Quarries.

I did plan to come up with a way to address it, but have not had time.

**Comment by Mohron** [comment]
The problem with it is new blocks are being generated faster than they are being "eaten" which makes the machine completely useless once it reaches a pool of lava. How you manage liquids is your business and I'm glad to hear you have efficiency in mind. I don't think that you intended to have a non-functional device due to this design choice.

**Comment by Mordenkainen** [comment]
It is in no way non-functional. It requires the user to actually participate in the activity and clean out the lava themselves.

**Comment by Mohron** [comment]
With no mention of such a requirement in the thauminomicon entry, or really information available elsewhere this appears like a bug and frankly, such an expensive machine both crafting and operation, should not require manual player interaction. Also might I add that the bottom to top approach makes this much more difficult to achieve if not more of a headache than it is worth. If the machine started at the top and stopped upon reaching liquid, it would be easier to detect and remove for the player. I for one would rather not have to do extra work but if it will be required, it should at least be reasonable. Having to dig down to bedrock, going through a lava lake to find the source of the issue is not something anyone should have to do.

**Comment by Mordenkainen** [comment]
Hey, and there is another block in the mod that can create a hungry node and consume your base... Also not documented. The tag line for the mod is "Science and Magic. What could go wrong?", you just discovered one of those things!

**Comment by Mohron** [comment]
That's not entirely the same. You're creating a node, which in Thaumcraft has a chance to be one of many type, including a hungry node. If you don't think about the node you would be creating sharing the behaviors of the nodes already existing in the world, that's your fault. The eldritch consumer is a completely new device that generate essence from blocks. You don't need to tell a player more about essence and how it is generated from the mining of blocks because that has been covered with previous research.  A machine not being capable of doing it's job properly when it reaches something undesirable cannot be inferred from any of the devices referenced in the descriptive text. Most quarrys do not choke when they hit liquid.

The Eldritch Consumer is a great idea, but if you let it be worse than all other quarries in the game, what incentive will there be to ever build or use it?

**Comment by Alaberti** [comment]
I'm confused here, doesn't the device eat blocks, not liquids? I figured it would just try to ignore non-blocks anyhow, so if it ran into a lava lake or whatever it would just turn off? Either way, it's not a serious issue, just kind of an interesting quirk.

**Comment by Mordenkainen** [comment]
It attempts to eat everything in its path, it just doesnt get any aspects from fluids it eats.

**Comment by Mordenkainen** [comment]
Working on this now.

Still needs bug testing and a lot of cleanup, but here is what has changed thus far:
- Consumer now works from top to bottom.
- Consumer now plugs up holes in side walls that fluid is flowing through to prevent server lag. This could potentially be used to farm Terra, but I'm not too concerned.
- Consumer kills any non-player mobs in it's way. These mobs will drop items as normal for a non-player kill. (Don't let your pets get in the way of this thing!)
- Consumer will also eat all items in it's way. This includes mob drops and items that may be dropped by inventories it eats. This means the consumer could be used as an ultra fast but power hungry Alchemical Furnace using droppers, open crates, or similar blocks.
