### ISSUE TITLE
HEE Compatibility Issue: Ore Smelting XP

### ISSUE THREAD

**Issue by EmberQuill** [theflogat/Technomancy#178]
For some reason, Technomancy sets the smelting xp for various ores to 100 (it is usually a float between 0 and 1). This value is used in calculations for a combination Fortune/Autosmelting effect on Hardcore Ender Expansion's Scorching Pickaxe, causing it to drop hundreds of stacks of ingots for each ore block mined.

**Comment by Mordenkainen** [comment]
Technomany does not modify the XP values for any ores.

What leads you to believe it is Technomancy that is causing this?

**Comment by Mordenkainen** [comment]
Note, the XP value for ores was NOT being changed. The XP value of a furnace smelting recipe was, and this had the side effect of causing the issue.
