### ISSUE TITLE
Error in fml-client-latest.log

### ISSUE THREAD

**Issue by Drethic** [theflogat/Technomancy#182]
While doing a log review for another issue I found these lines and wanted to report them as stated in the log:
```
[19:24:30] [Client thread/INFO] [STDERR/technom]: [theflogat.technomancy.Technomancy:preInit:76]: Severe error, please report this to the mod author:
[19:24:30] [Client thread/INFO] [STDERR/technom]: [theflogat.technomancy.Technomancy:preInit:77]: java.lang.ArrayIndexOutOfBoundsException
```

Please let me know if you need additional information.

**Comment by Mordenkainen** [comment]
Looking at the code it looks like you may get this error if fo some reason you have more than 256 different types of potions. Have you added a bunch of mods that add potions? (Or perhaps just ine that adds a ton)

**Comment by Drethic** [comment]
We have the following mods that add potions ( or at least potion effects ):
Ars Magica 2
Blood Magic
Biomes O' Plenty
Botantia
Brewcraft
ForbiddenMagic
Growthcraft (Cellar)
Immersive Engineering
Technomancy
ThaumicExploration
Thaumic Tinkerer
Witchery

When I was updating configs for those ID's we had around 150 including the 23 from Minecraft.

Here is our mod list as of 0.5.6 ( when that happened ) in case I missed any that add potions:
http://pastebin.com/MnZ4Ewav

**Comment by Mordenkainen** [comment]
TBH I don't know exactly what the section of code is doing. It was added by @theflogat, I'm just guessing.

**Comment by theflogat** [comment]
Minecraft only allows for a small amount of potions which is an issue. Every mod authors can modify the potion array with reflection however to widen the amount of potion. Because that's what most people do, the code makes the potion array be able to hold 256 values.

This "error" can happen if someone has already made the array larger which I should probably have added a check for.

**Comment by Mordenkainen** [comment]
I can add that check on the next bug fix cycle (if there is one) if you would like.

At this point we seem pretty stable so I may not do a bug fix release unless something else is found.
