### ISSUE TITLE
Redstone Torch does not change Dynamo setting

### ISSUE THREAD

**Issue by Mordenkainen** [theflogat/Technomancy#33]
Right clicking on a dynamo with a redstone torch does not make the dynamo use a "low" redstone signal.

After some investigation I determined that the redstone state of the dynamo is set on the client side, and when you right click on the block with a redstone torch onBlockActivated is only called on the server side. onBlockActivated is called on both sides for the gunpowder and redstone.

I suspect that this is because the redstone torch is an ItemBlock and not an Item, so probably tries to place the torch after calling onBlockActivated on the server, fails because the dynamo is non-solid, and aborts at that point.

Some possible solutions might be:
- Set redstone state server side then sync it to the client
- Use a different item than a redstone torch

I did not fix it because I did not know what your thoughts would be on the best way to handle it.

**Comment by theflogat** [comment]
I'll look into it. It will probably be fixed with an event handler.
