### ISSUE TITLE
generateTagsFromArcaneRecipes Crash / Forge 1307 / Technomancy 0.9.0+

### ISSUE THREAD

**Issue by Alaberti** [theflogat/Technomancy#39]
http://pastebin.com/2xLJfPBe - occurs when scanning any vanilla Thaumcraft item (my tests usually involved empty warded jars)
http://pastebin.com/YZ6yvSA9 - occurs whenever a tool is placed into an Alchemical furnace

I referenced these issues with azanor here: https://github.com/Azanor/thaumcraft/issues/1634

Verified these issues are only present with your mod (edit: and dependencies) installed, affect SSP and SMP, and as far as I'm aware only cropped up after I updated CoFH Core, Thermal Expansion, and Thermal Foundation today to their release candidates (22 Feb).

**Comment by Mordenkainen** [comment]
Some questions:
Did you also update Forge when you updated the COFH mods?
Did you update Thaumcraft?

**Comment by Alaberti** [comment]
I had updated Thaumcraft to 4.2
2.3.5 and the CoFH mods to their RC1 candidates; they are are referenced in the crash logs. I did not update forge, however I have been using 1307 for a few weeks now.

**Comment by Alaberti** [comment]
Updated to the latest version and deleted my old config - this issue seems to have resolved itself. I'm going to largely blame being an idiot for forgetting to clear my old settings. I'm spoiled.

**Comment by theflogat** [comment]
Happens to everyone. Can't blame you.

**Comment by Alaberti** [comment]
Looks like I'm on to something either all - I managed to replicate this issue on 0.10b by setting all of the dynamos to false in the config and creating the crash. Returning the values to true doesn't cause the issue.

**Comment by theflogat** [comment]
I found the culprit. The next version will have this fixed.
