### ISSUE TITLE
Client crash when clicking blood dynamo after right clicking with gunpowder

### ISSUE THREAD

**Issue by Saereth** [theflogat/Technomancy#42]
Tried to right click the blood dynamo with gunpowder to set redstone, upon touch the dynamo after that the client crashes, reported by several people, here is a crash log:
http://pastebin.com/d0Zi4K03

Minecraft 1.7.10 0.9.0 technomancy, forge 1307, latest version of BloodMagic-1.7.10-1.3.0b-3

**Comment by Saereth** [comment]
Also seems to be fixed in v.10

**Comment by theflogat** [comment]
Yup
