### ISSUE TITLE
Severe Memory Link in Version 10.d

### ISSUE THREAD

**Issue by Alaberti** [theflogat/Technomancy#53]
Discovered a massive increase in memory usage with this version; normally, I run about 3.5GB (including heap) and I was experiencing upwards 7GB usage in the latest version. Verified with two other players and they were noticing the same issue. I'm not sure what happened/changed but are you able to verify this on your end? I promise I'm not crazy ^_^

**Comment by Mordenkainen** [comment]
What was the "previous" version you were using? 10.C?

**Comment by Alaberti** [comment]
That is correct, and I haven't had any noticeable memory issues.

**Comment by Mordenkainen** [comment]
What items and blocks from Technomancy are you using?

If there is a leak it is probably with a particular block/item so no one will see it unless that block is placed in the world.

A quick test in an empty test world shows virtually no difference in memory usage.

**Comment by Alaberti** [comment]
None of them, we're on a reasonably fresh world at the moment but upon further inspection even in 10.c there is still a noticeable increase in memory. We noticed it when we updated it and Botania. I think this will require further research, I'll close this for now and update when I know more.

**Comment by Alaberti** [comment]
Confirmed the culprit was Witching Gadgets. FYI.
