### ISSUE TITLE
Quantum Jars support for Essentia Locus (Automagy)

### ISSUE THREAD

**Issue by Alaberti** [theflogat/Technomancy#58]
https://github.com/Tuhljin/Automagy/issues/17#issuecomment-86791487 courtesy of @misterfixit.

**Comment by Mordenkainen** [comment]
After some discussion with the mod author of Automagy, this should be fixed if the Quantum Jars are re-implemented to extend TileJarFillable. This is planned as part of the Thaumcraft API work.

I suggest this issue be left open until that work is done, just to keep track of it.
