### ISSUE TITLE
Can't pump items in Advanced Deconstruction Table

### ISSUE THREAD

**Issue by kesppr** [theflogat/Technomancy#71]
The title pretty much says it all, I tried EnderIO conduits and vanilla hoppers as of now and nothing has worked.
I'm guessing it might be related to the fact that the Research Points are given to whoever places the items inside (not sure if this is the case), but as this is a block meant to automate things it might be better to allow pumping in items and leave the RPs in a buffer to be picked up via right click, or to allow to set a destination player via GUI.
Alternatively it could be possible to allow golems with the fill core to put items in and to give the RPs to whichever player placed the golem.

**Comment by theflogat** [comment]
It can be fully automated. Fixed the fact that items can't be pumped in and it adds research points to the player who placed the table.
