### ISSUE TITLE
Thaumonomicon crashes when I click your tab

### ISSUE THREAD

**Issue by Azutte** [theflogat/Technomancy#72]
edit: "entire client" crashes, also I'm running COFH Core 3.0.2-262, Botania r1.6-187, and Thaumcraft 4.2.3.5

I don't have Thermal Expansion installed.
[here's the crashlog](http://pastebin.com/nWLD8XvM)

**Comment by Azutte** [comment]
I also crash when I right click with a "mana condensate bucket".

**Comment by Mordenkainen** [comment]
Can you post a crash report for the mana condensate bucket?

**Comment by Azutte** [comment]
http://pastebin.com/pMf41rzk

**Comment by Mordenkainen** [comment]
OK, tracked down the source of the issues. I hope to submit a fix shortly and it should be included in the next weekly build.

**Comment by Mordenkainen** [comment]
Closed via pull request #74
