### ISSUE TITLE
Mekanism Support? 

### ISSUE THREAD

**Issue by Gazmer** [theflogat/Technomancy#73]
I would like to request for the recipes for Thermal Expansion Items to allow Mekanism alternatives.
Examples: That I found and would suggest.
(Thermal : Mekanism)
Energy Cells : Energy Cubes
Machine Frame : Steel Casing
Redstone Reception Coil : Enriched Alloy
Redstone Flux Capacitor : Energy Tablet
And maybe some for your custom items
(Technomancy:Alternative)
Blood Coil : Blood Alloy
Enchanted Coil : Enchanted Alloy

Edit:
This might help fix #72. giving us a second alternative to Thermal Expansion and allowing a choice from 2 dependancies. (Talking completely out of my a** here don't hesitate to say that is stupid)

**Comment by Mordenkainen** [comment]
This is not a bad idea, but will require some additional infrastructure to be built up to support it.

In addition to adding the support for the Mekanisim items, config options for which set of recipes to use would also have to be added to handle situations where both Mekanisim and Thermal Expansion were detected. (Or to allow the use of the "vanilla" recipes even when one of these mods is loaded)

**Comment by Mordenkainen** [comment]
FYI - #72 was due to an "order of operations" oversight on my part, and a bad research entry in the Thaumonomicon. It was unrelated to the items used for recipes.

**Comment by Gazmer** [comment]
Sorry having having Foundation and Expansion fixed it so I made assumptions.
