### ISSUE TITLE
Crash on Modded Server (version 0.10.k)

### ISSUE THREAD

**Issue by Gazmer** [theflogat/Technomancy#87]
Runs fine in single player but as soon as I try to run on a server it crashes.
Server runs fine without Technomancy and the log points to Technomancy as well.

crash-log: http://sharetext.org/zF4C

**Comment by Mordenkainen** [comment]
Can you repost this on pastebin or something? I can't see your crash report.

**Comment by Gazmer** [comment]
Sorry had no idea what you guys preffered and used the first site I saw. 

Pastebin: http://pastebin.com/zCA5i2K6

**Comment by Mordenkainen** [comment]
Thanks!

Not so much a preference as the site you used appears to have already deleted your paste or something.

**Comment by Gazmer** [comment]
So anything on this, is it a Technomancy problem or is it my fault for trying to get too many mods working together?

**Comment by Mordenkainen** [comment]
I'm fairly sure it is caused by Technomancy, and I believe theflogat is working on it.
