### ISSUE TITLE
Crash when opening Thaumonomicon tab

### ISSUE THREAD

**Issue by Mordstreich** [theflogat/Technomancy#88]
Hi, I get a crash when clicking on the Technomancy tab of the Thaumonomicon, all others are fine.

I can spawn everything ok with NEI or creative.

Crashlog here: http://pastebin.com/kMxx0eP2

I'm running Resonant Rise 3 with a few extras.

Cheers, Mord

**Comment by Mordenkainen** [comment]
According to the crash report you are running Technomancy 0.10.I.

Technomancy 0.10.K is released and should fix the issue.
