### ISSUE TITLE
NEI Display issue for Electric Wand

### ISSUE THREAD

**Issue by Mordenkainen** [theflogat/Technomancy#93]
Electric wand is not displayed in the NEI GUI. Instead a wooden wand with a capacity of 25 is displayed. I suspect NEI is reading the items to display prior to the electric wand core being registered, and causes a wand with a default wooden core to be displayed instead.

The Creative menu displays the wands correctly.

**Comment by RoloEdits** [comment]
My Scepter Just Turned Into An Iron Capped Wand. It Can be Recharged By RF But Now Has All the Stats Of An Iron Caped Wand Like The Capacity And Efficiency. It Still Performs As A Wrench.

![2015-07-11_04 37 58](https://cloud.githubusercontent.com/assets/12489689/8633779/2977640c-2790-11e5-8a23-ac16f77f5f09.png)


![2015-07-11_04 38 10](https://cloud.githubusercontent.com/assets/12489689/8633780/30573ae0-2790-11e5-8cd5-853ae3dd2412.png)

**Comment by Mordenkainen** [comment]
Closing this issue as it appears to be resolved

**Comment by Mordenkainen** [comment]
Nope, still not fixed
