### ISSUE TITLE
Crash on applying a label [Technomancy 10k, Forge 1408]

### ISSUE THREAD

**Issue by Alaberti** [theflogat/Technomancy#96]
Got this error on adding metallum to a quantum jar and attempting to apply a label. It uh...did not like that and crashed to desktop.
http://pastebin.com/raw.php?i=rSWJx2dT

Attempting to re-enter the area causes it to keep crashing.
http://pastebin.com/raw.php?i=jWi2vEDr

**Comment by theflogat** [comment]
Thanks for reporting, will be fixed next version.

**Comment by Mordenkainen** [comment]
There are several reports of this exception (and some related ones) on openeye. Just an FYI.

**Comment by Alaberti** [comment]
You two have no idea how excited I get when I break stuff lol

**Comment by Mordenkainen** [comment]
Humorously enoungh. Breaking software is what i get paid to do for a living.

**Comment by Mordenkainen** [comment]
Problem reported with beta 10.k, but problem still exists in beta 10.l:
http://openeye.openmods.info/crashes/12ffe548748c00367f4aec165ada95d2

[BlockContainerAdvanced Line#55] https://github.com/theflogat/Technomancy/blob/master/src/main/java/theflogat/technomancy/common/blocks/base/BlockContainerAdvanced.java#L55 does not check if the item has a stackCompound before writing to it.
