### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by HyperMan19680** [theflogat/Technomancy#97]
This is my Node Fabricator setup. Both of them are setup with Terra vis, and both have the Chaos Gem inside them. Both have sufficient RF, but nothing is being added. What am I missing?
http://prntscr.com/7dcuyi

**Comment by Mordenkainen** [comment]
The image appears corrupt, so it's tough for me to make anything out... So how about some questions:

1. Are the center cores of the Node Fabricators spinning?
2. Are there lightning bolts shooting from either side to the other?
3. I see not Essentia tubes connected to either fabricator. Are you using Essenita coils or something?
4. In your picture you show the Waila info for the node, but I would need the info for the Fabricators.

Based on the picture it is very hard to tell if your placement, wiring, or tube systems are correct.

Here is what your picture looks like BTW:
![8gb1l42](https://cloud.githubusercontent.com/assets/826358/8009114/5ad0a26c-0b74-11e5-90a2-48e15a38767f.png)

**Comment by HyperMan19680** [comment]
Lighting and spinning is occurring, and I am using coils. My Fabricators both have 255 Terra Essentia. But what I DID notice is that the WAILA's displaed mode for the fabricators continued to show Charging Mode, even with the Potency Gems. Maybe that is the problem?

**Comment by Mordenkainen** [comment]
So you have coils connected to the Fabricators (I can't see them in the picture) and linked to some of those jars?

You have upgraded both Fabricators with Potency Gems, and the Waila display shows them as being upgraded/having a potency gem?

The Waila display identifies the redstone mode as "Low" and lists the Fabricator as being "Enabled"?

Does the Waila RF display should it as being full charged? Or is it reading just below fully charged?

**Comment by Mordenkainen** [comment]
Ok, found the issue and will make a fix. In the short term you can work around the issue by clicking on the Node Fabricators with gunpowder.

**Comment by Mordenkainen** [comment]
Node Fabricator fails to properly check redstone signal state.
